I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script call
    call image_buttons
  File "game/script.rpy", line 26, in script call
    call image_buttons
ScriptError: could not find label 'image_buttons'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 26, in script call
    call image_buttons
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\ast.py", line 1725, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 26, in script call
    call image_buttons
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'image_buttons'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Feature_Test_1 1.0
Tue Nov  7 20:30:36 2023
