I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/introduction/chapter_1.rpy", line 175, in script call
    $ visual_novel.stop_until_forum_precondition()
  File "game/story/introduction/chapter_1.rpy", line 289, in script
    python:
  File "game/story/introduction/chapter_1.rpy", line 294, in <module>
    forum.story_thread.replies.append(final_intro_reply)
AttributeError: 'int' object has no attribute 'replies'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/introduction/chapter_1.rpy", line 175, in script call
    $ visual_novel.stop_until_forum_precondition()
  File "game/story/introduction/chapter_1.rpy", line 289, in script
    python:
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/story/introduction/chapter_1.rpy", line 294, in <module>
    forum.story_thread.replies.append(final_intro_reply)
AttributeError: 'int' object has no attribute 'replies'

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Production 1.0
Sat Feb 24 21:11:05 2024
