I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/introduction/chapter_1.rpy", line 164, in script
    $ visual_novel.stop_until_forum_precondition()
  File "game/story/introduction/chapter_1.rpy", line 164, in <module>
    $ visual_novel.stop_until_forum_precondition()
  File "game/persistant code/managers.rpy", line 139, in stop_until_forum_precondition
    renpy.pause()
TypeError: Too many arguments in call (expected 0, got 1).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/introduction/chapter_1.rpy", line 164, in script
    $ visual_novel.stop_until_forum_precondition()
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/story/introduction/chapter_1.rpy", line 164, in <module>
    $ visual_novel.stop_until_forum_precondition()
  File "game/persistant code/managers.rpy", line 139, in stop_until_forum_precondition
    renpy.pause()
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\exports.py", line 1638, in pause
    rv = renpy.ui.interact(mouse='pause', type='pause', roll_forward=roll_forward, pause=delay, pause_modal=modal)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\core.py", line 4055, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\screen.py", line 476, in visit_all
    callback(self)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\core.py", line 4055, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\screen.py", line 487, in per_interact
    self.update()
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\screen.py", line 680, in update
    self.screen.function(**self.scope)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\ast.py", line 296, in apply_arguments
    return parameters.apply(args, kwargs, ignore_errors)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\ast.py", line 158, in apply
    raise TypeError("Too many arguments in call (expected 0, got %d)." % len(args))
TypeError: Too many arguments in call (expected 0, got 1).

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Production 1.0
Tue Feb 27 09:51:35 2024
