I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/introduction/script.rpy", line 74, in script
    e "1"
  File "game/story/introduction/script.rpy", line 74, in script
    e "1"
  File "renpy/common/00action_control.rpy", line 237, in __call__
    renpy.hide_screen(self.screen, layer=self._layer)
Exception: Unknown layer <store.Thread object at 0x0000000005202c40>.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\main.py", line 670, in main
    run(restart)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\main.py", line 144, in run
    renpy.execution.run_context(True)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "game/story/introduction/script.rpy", line 74, in script
    e "1"
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "game/story/introduction/script.rpy", line 74, in script
    e "1"
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\character.py", line 1352, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\character.py", line 1003, in do_display
    display_say(who,
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\character.py", line 693, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\core.py", line 4538, in interact_core
    rv = renpy.display.focus.mouse_handler(ev, x, y)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\focus.py", line 604, in mouse_handler
    return change_focus(new_focus, default=default)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\focus.py", line 523, in change_focus
    current.unfocus(default=default)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\behavior.py", line 1009, in unfocus
    run(self.unhovered)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\behavior.py", line 379, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_control.rpy", line 237, in __call__
    renpy.hide_screen(self.screen, layer=self._layer)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\screen.py", line 1341, in hide_screen
    screen = get_screen(tag, layer)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\screen.py", line 1120, in get_screen
    sd = sl.get_displayable_by_tag(layer, tag)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\display\core.py", line 1652, in get_displayable_by_tag
    raise Exception("Unknown layer %r." % layer)
Exception: Unknown layer <store.Thread object at 0x0000000005202c40>.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Production 1.0
Sat Dec 23 21:20:03 2023
