I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/introduction/hw_day_2.rpy", line 158, in script
    python:
  File "game/story/introduction/hw_day_2.rpy", line 161, in <module>
    make_day_2_forum().thread_3.replies.append(comp1_reply_7)
AttributeError: 'NoneType' object has no attribute 'thread_3'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/introduction/hw_day_2.rpy", line 158, in script
    python:
  File "C:\Users\carol\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\carol\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/story/introduction/hw_day_2.rpy", line 161, in <module>
    make_day_2_forum().thread_3.replies.append(comp1_reply_7)
AttributeError: 'NoneType' object has no attribute 'thread_3'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Production 1.0
Tue Feb 27 18:20:54 2024
