I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story_chapters/intro_tutrotial/script.rpy", line 24, in script call
    call test_screens
  File "game/story_chapters/intro_tutrotial/test_screens.rpy", line 20, in script
    $ print(singeton.name + "work please")
  File "game/story_chapters/intro_tutrotial/test_screens.rpy", line 20, in <module>
    $ print(singeton.name + "work please")
NameError: name 'singeton' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story_chapters/intro_tutrotial/script.rpy", line 24, in script call
    call test_screens
  File "game/story_chapters/intro_tutrotial/test_screens.rpy", line 20, in script
    $ print(singeton.name + "work please")
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files\renpy-8.1.1-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/story_chapters/intro_tutrotial/test_screens.rpy", line 20, in <module>
    $ print(singeton.name + "work please")
NameError: name 'singeton' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Failed To Send 1.0
Tue Nov 14 16:47:31 2023
